//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.15 at 11:22:14 AM CET 
//


package l2trunk.gameserver.data.xml.jaxb.soulcrystals;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for crystalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="crystalType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="occupation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="item_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="next_item_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cursed_next_item_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "crystalType", propOrder = {
    "value"
})
public class CrystalType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "occupation")
    protected String level;
    @XmlAttribute(name = "item_id")
    protected String itemId;
    @XmlAttribute(name = "next_item_id")
    protected String nextItemId;
    @XmlAttribute(name = "cursed_next_item_id")
    protected String cursedNextItemId;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemId(String value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the nextItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextItemId() {
        return nextItemId;
    }

    /**
     * Sets the value of the nextItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextItemId(String value) {
        this.nextItemId = value;
    }

    /**
     * Gets the value of the cursedNextItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCursedNextItemId() {
        return cursedNextItemId;
    }

    /**
     * Sets the value of the cursedNextItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCursedNextItemId(String value) {
        this.cursedNextItemId = value;
    }

}
